[package]
name = "hibi2"
version = "0.1.0"
authors = ["Sam Stokes <me@samstokes.co.uk>"]
edition = "2018"

[dependencies]
diesel = { version = "1.0.0", features = ["postgres", "chrono"] }
dotenv = "0.9.0"
chrono = "0.4.6"
regex = "1"
lazy_static = "1.1.0"
