// generated by `diesel print-schema`
// and hand-tweaked
// N.B. this won't be auto updated because we have no migrations here

#![allow(proc_macro_derive_resolution_fallback)]

// "Column `email` cannot be named the same as its table."
//table! {
//email (id) {
//id -> Int4,
//email -> Varchar,
//user -> Nullable<Int8>,
//verkey -> Nullable<Varchar>,
//}
//}

//table! {
//estimate (id) {
//id -> Int4,
//task -> Int8,
//pomos -> Int8,
//}
//}

table! {
    #[sql_name = "ext_task_with_bigid"]
    ext_tasks (id) {
        #[sql_name = "bigid"]
        id -> Int8,
        #[sql_name = "user"]
        user_id -> Int8,
        ext_id -> Varchar,
        ext_source_name -> Varchar,
        ext_url -> Nullable<Varchar>,
        ext_status -> Nullable<Varchar>,
    }
}

//table! {
//note (id) {
//id -> Int4,
//body -> Varchar,
//task -> Int8,
//created_at -> Timestamp,
//}
//}

//table! {
//plan (id) {
//id -> Int4,
//user -> Int8,
//body -> Varchar,
//created_at -> Timestamp,
//done_at -> Nullable<Timestamp>,
//}
//}

table! {
    #[sql_name = "task"]
    tasks (id) {
        id -> Int4,
        #[sql_name = "user"]
        user_id -> Int8,
        title -> Varchar,
        pomos -> Int8,
        scheduled_for -> Timestamp,
        done_at -> Nullable<Timestamp>,
        active -> Bool,
        order -> Int8,
        schedule -> Varchar,
        #[sql_name = "ext_task"]
        ext_task_id -> Nullable<Int8>,
    }
}

table! {
    #[sql_name = "user_with_bigid"]
    users (id) {
        #[sql_name = "bigid"]
        id -> Int8,
        ident -> Varchar,
        password -> Nullable<Varchar>,
        time_zone -> Nullable<Varchar>,
        features -> Varchar,
    }
}

//joinable!(email -> user (user));
//joinable!(estimate -> task (task));
joinable!(ext_tasks -> users (user_id));
//joinable!(note -> task (task));
//joinable!(plan -> user (user));
joinable!(tasks -> ext_tasks (ext_task_id));
joinable!(tasks -> users (user_id));

allow_tables_to_appear_in_same_query!(ext_tasks, tasks, users,);
//allow_tables_to_appear_in_same_query!(email, estimate, ext_task, note, plan, task, user,);
